version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - $NODE_PORT:$NODE_PORT
    restart: always
    env_file: ./.env
    environment:
      - DB_HOST=MONGODB_HOST
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_PORT
    depends_on:
      - db
    volumes:
      - ./backend:/usr/src/app

  db:
    image: mongo:latest
    ports:
      - $MONGODB_PORT:$MONGODB_PORT
    restart: always
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    volumes:
      - db-data:/data/db

volumes: 
  db-data: